const fieldHelp: Record<string, string> = {
  page_key: "页面唯一标识，前台靠它找内容。一般不要改，改错后页面会读不到后台内容。",
  path: "这个内容对应的前台路径，用来做 SEO 检查和预览。",
  slug: "网址里的短链接，只建议用小写英文、数字和短横线。已上线页面随便改链接标识会影响旧链接。",
  status: "只有“已发布”会在前台显示；“草稿”不会对外展示；“已归档”会隐藏。",
  sort_order: "排序数字，数字越小越靠前。建议 10、20、30 这样留空位，方便以后插入。",
  title_zh: "中文标题，通常显示在页面主标题、卡片标题或模块标题。",
  title_en: "英文标题，英文站会优先显示这里。",
  subtitle_zh: "中文小标题，常用于首屏上方短标签或模块副标题。",
  subtitle_en: "英文小标题，英文站会优先显示这里。",
  excerpt_zh: "中文摘要，常用于列表卡片和页面简介。",
  excerpt_en: "英文摘要，英文站列表卡片会优先显示这里。",
  description_zh: "中文说明文案，通常显示在页面首屏或模块说明。",
  description_en: "英文说明文案，英文站会优先显示这里。",
  content_zh: "中文正文或补充说明。有些页面支持 {count}、{category}、{description} 这类占位符。",
  content_en: "英文正文或补充说明。英文站会优先显示这里。",
  cta_title_zh: "中文行动引导标题，通常在页面底部行动区显示。",
  cta_title_en: "英文行动引导标题，英文站会优先显示这里。",
  cta_description_zh: "中文行动引导说明，引导用户询价或联系。",
  cta_description_en: "英文行动引导说明，英文站会优先显示这里。",
  seo_title_zh: "中文 SEO/GEO 标题，显示在浏览器标题和搜索结果里。建议包含地区、服务和品牌，不要只翻译英文。",
  seo_title_en: "英文 SEO 标题，英文站会优先显示这里。",
  seo_description_zh: "中文 SEO/GEO 描述，给搜索引擎、分享卡片和 AI 摘要使用。要写清服务地区、适合对象、服务范围和下一步。",
  seo_description_en: "英文 SEO 描述，英文站会优先显示这里。",
  seo_keywords_zh: "中文 SEO 关键词，用逗号分隔即可。优先放中文地区词、服务词和高意向搜索词。",
  seo_keywords_en: "英文 SEO 关键词，用英文逗号分隔即可。",
  image_url: "图片地址。建议用媒体库上传后选择，避免外链失效。",
  hero_image_url: "页面首屏大图地址。建议用横图，避免移动端裁切太严重。",
  cover_image_url: "列表卡片或文章封面图。",
  alt_zh: "中文图片说明，给搜索引擎和无障碍阅读使用。",
  alt_en: "英文图片说明，英文站会优先使用这里。",
  items_zh: "中文列表/卡片内容。前台不同页面会把它显示成卖点、补充说明或扩展内容。",
  items_en: "英文列表/卡片内容，英文站会优先显示这里。",
  primary_url: "主按钮跳转地址，例如 /quote。",
  secondary_url: "副按钮跳转地址，例如 WhatsApp 链接或 /contact。",
  button_url: "按钮点击后跳转的链接。",
  rating: "客户评价星级，通常填 1 到 5。",
  project_id: "关联案例 ID。不会直接显示给客户，只用于后台关联。",
  related_projects: "落地页关联案例卡片，会显示在前台落地页。",
  projects: "地区页案例卡片，会显示在前台地区页面。",
  faqs_zh: "中文常见问题列表，会显示在对应详情页或落地页。",
  faqs_en: "英文常见问题列表，英文站会优先显示这里。",
  benefits_zh: "中文优势列表，一行或一条就是一个卖点。",
  benefits_en: "英文优势列表，英文站会优先显示这里。",
  process_steps_zh: "中文服务步骤，会显示在服务详情页。",
  process_steps_en: "英文服务步骤，英文站会优先显示这里。",
  suitable_for_zh: "中文适用场景列表。",
  suitable_for_en: "英文适用场景列表，英文站会优先显示这里。",
  common_projects_zh: "中文常见项目列表。",
  common_projects_en: "英文常见项目列表，英文站会优先显示这里。",
  scope_items_zh: "中文服务范围列表，会显示在服务详情页。",
  scope_items_en: "英文服务范围列表，英文站会优先显示这里。",
  client_need_zh: "中文客户需求说明，用在案例详情页。",
  client_need_en: "英文客户需求说明，英文站会优先显示这里。",
  highlights_zh: "中文项目亮点，一行一个。",
  highlights_en: "英文项目亮点，英文站会优先显示这里。",
  materials: "案例使用材料，一行一个。",
  scope: "案例施工范围，一行一个。",
  property_types: "地区页适合的房产类型，一行一个。",
  common_needs: "地区页常见需求，一行一个。",
  construction_notes_zh: "中文地区施工说明。",
  construction_notes_en: "英文地区施工说明，英文站会优先显示这里。",
  tags: "博客标签，一行一个，用于分类和搜索。",
  published_at: "发布时间。发布文章时如果为空，后台会自动用当前时间。",
};

const tableHelp: Record<string, string> = {
  site_pages: "管理页面级内容，例如页面标题、首屏文案、SEO 和行动引导。前台已接入的动态页面会优先显示这里的内容。",
  home_sections: "管理首页模块内容，比如统计数据、为什么选择我们等。",
  faqs: "管理常见问题。页面标识为 home 的内容显示在首页，页面标识为 general 的内容显示在常见问题页面。",
  before_after_items: "管理首页改造前后对比图片。",
  brand_partners: "管理首页品牌图标区域。",
  hero_slides: "管理首页首屏按钮文案和链接。首页首屏媒体固定播放视频，不再读取这里的图片，避免后台图片覆盖视频。",
  services: "管理服务列表和服务详情页内容。",
  projects: "管理案例列表和案例详情页内容，案例图片在下方项目图片区域管理。",
  materials: "管理材料库列表、材料分类和材料详情页内容。",
  blog_posts: "管理博客列表和博客详情页内容。",
  testimonials: "管理首页客户评价。",
  service_areas: "管理地区页，例如 Kuala Lumpur、Selangor 等服务区域页面。",
  landing_pages: "管理 SEO 落地页，例如厨房、办公室、仓库货架等专题页。",
  leads: "管理联系页提交的客户咨询。",
  quote_requests: "管理报价页提交的报价请求。",
  translation_jobs: "查看自动生成英文的记录、失败原因和重试入口。正文内容请到对应内容编辑页修改。",
};

export const getAdminFieldHelp = (field: string) => {
  const normalized = field.replace(/_(zh|en)$/, "");
  return fieldHelp[field] || fieldHelp[normalized] || null;
};

export const getAdminTableHelp = (table: string) => tableHelp[table] || null;
