export const adminSeoManagerText = {
  technicalPageTitle: { en: "Sitemap / Robots / llms.txt", zh: "站点地图 / Robots / llms.txt" },
  technicalPageDescription: {
    en: "Check public search entry files and confirm that search engines and AI summary systems can read the correct pages.",
    zh: "检查公开搜索入口文件，确认搜索引擎和 AI 摘要系统能读到正确页面。",
  },
  technicalPageHelp: {
    en: "This page shows technical file status, not normal content editing. sitemap.xml and llms.txt are generated by scripts, while robots.txt is a fixed rules file. Confirm search impact before changing rules.",
    zh: "这个页面是技术文件状态页，不是普通内容编辑器。sitemap.xml 和 llms.txt 由脚本生成，robots.txt 是固定规则文件；改规则前要先确认会不会影响搜索收录。",
  },
  backSeo: { en: "Back to SEO check", zh: "返回 SEO 检查" },
  openSitemap: { en: "Open sitemap.xml", zh: "打开 sitemap.xml" },
  openRobots: { en: "Open robots.txt", zh: "打开 robots.txt" },
  publicFilesTitle: { en: "Public technical files", zh: "公开技术文件" },
  publicFilesDescription: {
    en: "These files directly affect search engine crawling, AI summary reading, and admin page blocking.",
    zh: "这些文件直接影响搜索引擎抓取、AI 摘要读取和后台页面屏蔽。",
  },
  view: { en: "View", zh: "查看" },
  workflowTitle: { en: "Generation and verification flow", zh: "生成和验证流程" },
  workflowDescription: {
    en: "The admin currently handles viewing and jumping. File contents are generated by repository scripts to avoid missed pages from manual edits.",
    zh: "后台目前负责查看和跳转，文件内容由仓库脚本生成，避免人工改漏页面。",
  },
  currentBoundaryTitle: { en: "Current boundary", zh: "当前边界" },
  currentBoundaryDescription: {
    en: "This is not a new page entry point or a visual sitemap editor. Its purpose is to centralize sitemap, robots, and llms.txt entries and generation rules into one admin page, instead of mixing them with SEO content checks.",
    zh: "这里不是新增页面入口，也不是可视化编辑 sitemap 的地方。它的作用是把 sitemap、robots、llms.txt 的入口和生成规则集中到一个独立后台页面，避免和 SEO 内容检查混在一起。",
  },
  auditPageTitle: { en: "SEO / GEO Chinese Optimization Manager", zh: "SEO / GEO 中文优化管理" },
  auditPageDescription: {
    en: "Check Chinese titles, descriptions, keywords, regional signals, image alt text, and AI-readable summaries, with a focus on making Chinese pages independent rather than secondary to English SEO.",
    zh: "检查中文标题、描述、关键词、地区信号、图片说明和 AI 可读摘要，重点保证中文页面不是英文 SEO 的附属品。",
  },
  auditPageHelp: {
    en: "SEO mainly serves traditional search results. GEO here also covers generative search summaries and local regional signals. Admin checks only warn about risk; final copy still needs human review for natural, accurate, non-exaggerated language.",
    zh: "SEO 主要照顾传统搜索结果；GEO 这里同时指生成式搜索摘要和本地地区信号。后台检查只提示风险，最终仍要人工确认文案自然、准确、不夸大。",
  },
  sitemapRobots: { en: "Sitemap / Robots", zh: "站点地图 / Robots" },
  refreshing: { en: "Refreshing...", zh: "刷新中..." },
  refresh: { en: "Refresh", zh: "刷新" },
  filterAll: { en: "All", zh: "全部" },
  filterMissing: { en: "Missing only", zh: "只看缺失" },
  filterZh: { en: "Chinese SEO issues", zh: "中文 SEO 问题" },
  filterGeo: { en: "GEO region issues", zh: "GEO 地区问题" },
  filterAi: { en: "AI readability issues", zh: "AI 可读问题" },
  filterOk: { en: "Passed only", zh: "只看通过" },
  filterLabel: { en: "SEO / GEO issue filter", zh: "SEO / GEO 问题筛选" },
  checkContent: { en: "Checked content", zh: "检查内容" },
  missing: { en: "Missing", zh: "有缺失" },
  zhSeo: { en: "Chinese SEO", zh: "中文 SEO" },
  geoRegion: { en: "GEO region", zh: "GEO 地区" },
  passed: { en: "Passed", zh: "通过" },
  loading: { en: "Loading SEO / GEO data...", zh: "正在加载 SEO / GEO 数据..." },
  guidanceFormula: { en: "{title} formula: {formula}", zh: "{title} 写法：{formula}" },
  guidanceMustInclude: { en: "Must include: {mustInclude}", zh: "必须交代：{mustInclude}" },
  seoGeoPassed: { en: "SEO / GEO passed", zh: "SEO / GEO 通过" },
  edit: { en: "Edit", zh: "编辑" },
  chineseFrontendPage: { en: "Chinese frontend page", zh: "中文前台页" },
  duplicateSlug: { en: "Duplicate slug", zh: "链接标识重复" },
} as const;

export const adminSeoStrategyCards = {
  en: {
    zhFirst: {
      title: "Chinese SEO first",
      body: "Chinese titles and descriptions should not simply translate English. Write directly for Chinese-speaking customers and explain service, location, suitable audience, and next step.",
      example: "Example: Kuala Lumpur Kitchen Renovation | Custom Cabinets and Old Kitchen Upgrade | FLASH CAST",
    },
    geoSignal: {
      title: "GEO regional signals",
      body: "Every important page should include a real service area such as Kuala Lumpur, Selangor, or Klang Valley, so local search and AI summaries can identify service coverage.",
      example: "Description example: Serving Kuala Lumpur, Selangor, and Klang Valley, suitable for condos, terrace houses, offices, and shop renovations.",
    },
    aiReadable: {
      title: "AI-readable content",
      body: "GEO also needs to support AI search summaries. Pages should clearly state service coverage, suitable projects, process, materials, quote conditions, and FAQ, not just slogans.",
      example: "Keep factual boundaries such as quotes depending on site condition, size, material, and approval requirements.",
    },
  },
  zh: {
    zhFirst: {
      title: "中文 SEO 优先",
      body: "中文标题和描述不要只翻译英文，要直接写给华语客户看，讲清服务、地点、适合对象和下一步。",
      example: "例：吉隆坡厨房装修 | 橱柜定制与旧厨房翻新 | FLASH CAST",
    },
    geoSignal: {
      title: "GEO 地区信号",
      body: "每个重要页面至少带一个真实服务地区，例如吉隆坡、雪兰莪或巴生谷，让本地搜索和 AI 摘要更容易判断服务范围。",
      example: "描述里写：服务吉隆坡、雪兰莪与巴生谷，适合公寓、排屋、办公室和店铺装修。",
    },
    aiReadable: {
      title: "AI 可读内容",
      body: "GEO 也要照顾 AI 搜索摘要。页面要有清楚的服务范围、适合项目、流程、材料、报价条件和 FAQ，不要只放宣传口号。",
      example: "描述里保留“报价需根据现场、尺寸、材料和审批要求确认”这类事实边界。",
    },
  },
} as const;

export const adminSeoTechnicalFileText = {
  en: {
    sitemap: {
      description: "A public page list submitted to Google, Bing, and AI search entry points.",
      check: "Only official /zh and /en pages should be included. Duplicate URLs, old URLs, or parameter URLs are not allowed.",
    },
    robots: {
      description: "Tells search engines which pages can be crawled and which admin pages must be blocked.",
      check: "Must block /admin while keeping public entries for sitemap.xml and llms.txt.",
    },
    llms: {
      description: "Site description and canonical link list for AI search and summary systems.",
      check: "Must include company identity, Sitemap URL, and Canonical URL List.",
    },
  },
  zh: {
    sitemap: {
      description: "提交给 Google、Bing 和 AI 搜索入口的公开页面清单。",
      check: "只收录正式的 /zh 和 /en 页面，不能有重复地址、旧地址或带参数的地址。",
    },
    robots: {
      description: "告诉搜索引擎哪些页面可以抓取，哪些后台页面必须屏蔽。",
      check: "必须屏蔽 /admin，同时保留 sitemap.xml 和 llms.txt 的公开入口。",
    },
    llms: {
      description: "给 AI 搜索和摘要系统读取的站点说明和标准链接列表。",
      check: "必须包含公司身份、Sitemap 地址和 Canonical URL List。",
    },
  },
} as const;

export const adminSeoTechnicalWorkflowText = {
  en: {
    generate: {
      title: "Generate",
      detail: "Regenerate sitemap.xml separately. The official build also automatically generates sitemap, seo-manifest, and llms.txt.",
    },
    verify: {
      title: "Verify",
      detail: "Check sitemap, robots, llms, canonical, structured data, and Chinese-English path consistency.",
    },
    publish: {
      title: "Publish",
      detail: "The build runs the SEO technical file generation flow first, and generated files are included in the public output.",
    },
  },
  zh: {
    generate: {
      title: "生成",
      detail: "单独重新生成 sitemap.xml。正式 build 前也会自动生成 sitemap、seo-manifest 和 llms.txt。",
    },
    verify: {
      title: "验证",
      detail: "检查 sitemap、robots、llms、canonical、结构化数据和中英文路径是否一致。",
    },
    publish: {
      title: "发布",
      detail: "构建时会先执行 SEO 技术文件生成流程，生成后的文件进入 public 输出。",
    },
  },
} as const;

export const adminSeoGuidanceByTableText = {
  en: {
    site_pages: {
      title: "Page-level content",
      formula: "Region + page topic + core service | FLASH CAST",
      mustInclude: "Chinese SEO title, Chinese description, Chinese keywords, frontend path, and Chinese image alt text.",
    },
    cms_pages: {
      title: "CMS pages",
      formula: "Region + page topic + core service | FLASH CAST",
      mustInclude: "CMS pages override old page content, so Chinese SEO, GEO regional terms, keywords, and real frontend paths must stay synced.",
    },
    services: {
      title: "Services",
      formula: "Region + service name + typical scenario | FLASH CAST",
      mustInclude: "Service type, suitable audience, Kuala Lumpur / Selangor / Klang Valley, and quote or enquiry next step.",
    },
    projects: {
      title: "Renovation projects",
      formula: "Region + space type + completed result | FLASH CAST project",
      mustInclude: "Project location, space type, construction scope, materials, or result highlights.",
    },
    materials: {
      title: "Material library",
      formula: "Material name + suitable space + renovation material | FLASH CAST",
      mustInclude: "Material usage, suitable spaces, maintenance or budget notes, and Malaysian renovation context.",
    },
    blog_posts: {
      title: "Blog posts",
      formula: "Customer question + Malaysia / Kuala Lumpur renovation guide | FLASH CAST",
      mustInclude: "Question answer, applicable area, decision advice, and internal link direction.",
    },
    service_areas: {
      title: "Service areas",
      formula: "Area name + renovation service + common project | FLASH CAST",
      mustInclude: "Specific city or area, common home or commercial spaces, and local approval or construction notes.",
    },
    landing_pages: {
      title: "SEO landing pages",
      formula: "Region + high-intent service keyword + enquiry action | FLASH CAST",
      mustInclude: "High-intent keywords, service coverage, suitable audience, project / FAQ / quote entry.",
    },
  },
  zh: {
    site_pages: {
      title: "页面级内容",
      formula: "地区 + 页面主题 + 核心服务 | FLASH CAST",
      mustInclude: "中文 SEO 标题、中文描述、中文关键词、前台路径、图片中文说明。",
    },
    cms_pages: {
      title: "CMS 页面",
      formula: "地区 + 页面主题 + 核心服务 | FLASH CAST",
      mustInclude: "CMS 页面会覆盖旧页面内容，必须同步中文 SEO、GEO 地区词、关键词和真实前台路径。",
    },
    services: {
      title: "服务项目",
      formula: "地区 + 服务名称 + 典型场景 | FLASH CAST",
      mustInclude: "服务类型、适合对象、吉隆坡/雪兰莪/巴生谷、报价或咨询下一步。",
    },
    projects: {
      title: "装修案例",
      formula: "地区 + 空间类型 + 完成结果 | FLASH CAST 案例",
      mustInclude: "案例地点、空间类型、施工范围、材料或结果亮点。",
    },
    materials: {
      title: "材料库",
      formula: "材料名称 + 适用空间 + 装修材料 | FLASH CAST",
      mustInclude: "材料用途、适合空间、维护或预算提示、马来西亚装修语境。",
    },
    blog_posts: {
      title: "博客文章",
      formula: "客户问题 + 马来西亚/吉隆坡装修指南 | FLASH CAST",
      mustInclude: "问题答案、适用地区、决策建议、内部链接方向。",
    },
    service_areas: {
      title: "服务地区",
      formula: "地区名 + 装修服务 + 常见项目 | FLASH CAST",
      mustInclude: "具体城市/区域、常见房型或商业空间、本地审批或施工注意点。",
    },
    landing_pages: {
      title: "SEO 落地页",
      formula: "地区 + 高意向服务词 + 可咨询动作 | FLASH CAST",
      mustInclude: "高意向关键词、服务范围、适合人群、案例/FAQ/报价入口。",
    },
  },
} as const;

export const adminSeoIssueLabels = {
  missingZhTitle: { en: "Missing Chinese SEO title", zh: "缺中文 SEO 标题" },
  zhTitleNoChinese: { en: "Chinese title has no Chinese words", zh: "中文标题没有中文词" },
  zhTitleTooLong: { en: "Chinese title is long; shorten it", zh: "中文标题偏长，建议压缩" },
  missingZhDescription: { en: "Missing Chinese SEO description", zh: "缺中文 SEO 描述" },
  zhDescriptionNoChinese: { en: "Chinese description has no Chinese words", zh: "中文描述没有中文词" },
  zhDescriptionTooShort: { en: "Chinese description is short", zh: "中文描述偏短" },
  missingZhKeywords: { en: "Missing Chinese SEO keywords", zh: "缺中文 SEO 关键词" },
  missingGeoTerms: { en: "Missing GEO regional terms such as Kuala Lumpur or Selangor", zh: "缺吉隆坡/雪兰莪等 GEO 地区词" },
  zhDescriptionWeakAi: { en: "Chinese description is too short-form; AI summary information is weak", zh: "中文描述太像短句，AI 摘要信息量弱" },
  missingImageAltZh: { en: "Image missing Chinese alt text", zh: "图片缺中文说明 alt" },
  missingSlug: { en: "Missing slug", zh: "缺链接标识" },
  missingEnTitle: { en: "Missing English SEO title", zh: "缺英文 SEO 标题" },
  enTitleTooLong: { en: "English title is long; shorten it", zh: "英文标题偏长，建议压缩" },
  missingEnDescription: { en: "Missing English SEO description", zh: "缺英文 SEO 描述" },
  enDescriptionTooShort: { en: "English description is short", zh: "英文描述偏短" },
} as const;

export const adminSeoSourceLabels = {
  en: {
    site_pages: "Page-level content",
    cms_pages: "CMS pages",
    services: "Services",
    projects: "Projects",
    materials: "Materials",
    blog_posts: "Blog posts",
    service_areas: "Service areas",
    landing_pages: "Landing pages",
  },
  zh: {
    site_pages: "页面级内容",
    cms_pages: "CMS 页面",
    services: "服务项目",
    projects: "装修案例",
    materials: "材料库",
    blog_posts: "博客文章",
    service_areas: "服务地区",
    landing_pages: "落地页",
  },
} as const;
