export const staticPaths = [
  "/",
  "/about",
  "/services",
  "/services/renovation",
  "/services/design",
  "/services/builtin",
  "/services/kitchen",
  "/services/bathroom",
  "/services/office",
  "/services/shoplot",
  "/services/artistic-coating",
  "/services/old-house",
  "/services/approval",
  "/materials",
  "/projects",
  "/process",
  "/faq",
  "/contact",
  "/quote",
  "/blog",
  "/privacy",
  "/terms",
  "/locations/kuala-lumpur",
  "/locations/selangor",
  "/locations/petaling-jaya",
  "/locations/subang-jaya",
  "/locations/puchong",
  "/locations/cheras",
  "/locations/mont-kiara",
  "/locations/bangsar",
  "/landing/flooring",
  "/landing/kitchen-cabinet",
  "/landing/office-renovation",
  "/landing/shop-renovation",
  "/landing/warehouse-shelving",
  "/landing/bathroom-renovation",
  "/landing/old-house-renovation",
];

export const materialCategorySlugs = [
  "kitchen-cabinets",
  "whole-house-custom",
  "furniture",
  "bathroom",
  "countertops-stone-surfaces",
  "flooring",
  "doors-windows",
  "wall-panels",
  "art-paint",
];

export const siteUrl = () => Deno.env.get("SITE_URL") || "https://flashcast.com.my";
