import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { readAdminRouteDefinitionPaths, readInteractionRoutes } from './lib/interaction-route-inventory.mjs';

// Frozen pre-refactor route identities protect every existing path and component,
// rather than accepting a matching total after a route disappears or changes.
const previousRoutes = [
  ["admin", "/admin", "AdminLogin + AdminLayout"],
  ["admin", "/admin/*", "AdminNotFound"],
  ["admin", "/admin/about", "AdminAboutEditor"],
  ["admin", "/admin/before-after", "AdminBeforeAfter"],
  ["admin", "/admin/blog", "AdminBlogList"],
  ["admin", "/admin/blog/:id", "AdminBlogEditor"],
  ["admin", "/admin/blog/new", "AdminBlogEditor"],
  ["admin", "/admin/brand-partners", "AdminBrandPartners"],
  ["admin", "/admin/cms", "AdminCmsBuilder"],
  ["admin", "/admin/content-health", "AdminContentHealth"],
  ["admin", "/admin/content/:type/:id?", "AdminContentEditor"],
  ["admin", "/admin/content/leads", "Navigate"],
  ["admin", "/admin/content/leads/:id", "Navigate"],
  ["admin", "/admin/content/quote_requests", "Navigate"],
  ["admin", "/admin/content/quote_requests/:id", "Navigate"],
  ["admin", "/admin/content/translation_jobs", "AdminTranslationJobs"],
  ["admin", "/admin/content/translation_jobs/:id", "AdminTranslationJobs"],
  ["admin", "/admin/dashboard", "AdminDashboard"],
  ["admin", "/admin/english-center", "AdminEnglishCenter"],
  ["admin", "/admin/faqs", "AdminFaqs"],
  ["admin", "/admin/furniture", "AdminFurnitureList"],
  ["admin", "/admin/furniture/:id", "AdminFurnitureEditor"],
  ["admin", "/admin/furniture/new", "AdminFurnitureEditor"],
  ["admin", "/admin/home", "AdminHomeEditor"],
  ["admin", "/admin/lead-reports", "AdminLeadReports"],
  ["admin", "/admin/leads", "AdminLeadList"],
  ["admin", "/admin/leads/:id", "AdminLeadDetail"],
  ["admin", "/admin/materials", "AdminMaterialList"],
  ["admin", "/admin/materials/:id", "AdminMaterialEditor"],
  ["admin", "/admin/materials/new", "AdminMaterialEditor"],
  ["admin", "/admin/media", "AdminMediaLibrary"],
  ["admin", "/admin/notifications", "AdminNotificationSettings"],
  ["admin", "/admin/pages", "AdminPages"],
  ["admin", "/admin/projects", "AdminProjectList"],
  ["admin", "/admin/projects/:id", "AdminProjectEditor"],
  ["admin", "/admin/projects/new", "AdminProjectEditor"],
  ["admin", "/admin/promotions", "AdminPromotionsEditor"],
  ["admin", "/admin/publish-center", "AdminPublishCenter"],
  ["admin", "/admin/quotes", "AdminQuoteList"],
  ["admin", "/admin/quotes/:id", "AdminQuoteDetail"],
  ["admin", "/admin/seo", "AdminSeoManager"],
  ["admin", "/admin/services", "AdminServiceList"],
  ["admin", "/admin/services/:id", "AdminServiceEditor"],
  ["admin", "/admin/services/new", "AdminServiceEditor"],
  ["admin", "/admin/settings", "AdminWebsiteSettings"],
  ["admin", "/admin/system-health", "AdminSystemHealth"],
  ["admin", "/admin/system-logs", "AdminSystemLogs"],
  ["admin", "/admin/users", "AdminUsers"],
  ["public", "/", "RootLanguageRedirect"],
  ["public", "/:lang", "Index"],
  ["public", "/:lang/*", "CmsDynamicPage"],
  ["public", "/:lang/about", "About"],
  ["public", "/:lang/before-after", "BeforeAfter"],
  ["public", "/:lang/blog", "Blog"],
  ["public", "/:lang/blog/:slug", "Suspense"],
  ["public", "/:lang/contact", "Contact"],
  ["public", "/:lang/faq", "FAQ"],
  ["public", "/:lang/furniture", "FurnitureShowcase"],
  ["public", "/:lang/furniture/:category", "FurnitureShowcase"],
  ["public", "/:lang/furniture/:category/:subcategory", "FurnitureShowcase"],
  ["public", "/:lang/furniture/product/:slug", "FurnitureProductDetail"],
  ["public", "/:lang/landing/:slug", "LandingPageRoute"],
  ["public", "/:lang/locations", "Locations"],
  ["public", "/:lang/locations/:slug", "LocationPage"],
  ["public", "/:lang/materials", "Materials"],
  ["public", "/:lang/materials/:slug", "MaterialDetail"],
  ["public", "/:lang/materials/category/:categorySlug", "MaterialCategoryPage"],
  ["public", "/:lang/materials/category/:categorySlug/:subcategorySlug", "MaterialSubcategoryPage"],
  ["public", "/:lang/privacy", "Privacy"],
  ["public", "/:lang/process", "Process"],
  ["public", "/:lang/products", "ProductsToMaterialsRedirect"],
  ["public", "/:lang/products/:slug", "ProductsToMaterialsRedirect"],
  ["public", "/:lang/projects", "Projects"],
  ["public", "/:lang/projects/:slug", "ProjectDetail"],
  ["public", "/:lang/promotions", "Promotions"],
  ["public", "/:lang/quote", "Quote"],
  ["public", "/:lang/services", "Services"],
  ["public", "/:lang/services/:slug", "ServiceDetail"],
  ["public", "/:lang/services/old-house", "OldHouseRenovation"],
  ["public", "/:lang/terms", "Terms"],
  ["public", "/*", "NotFound"],
  ["public", "/about", "LegacyLanguageRedirect"],
  ["public", "/before-after", "LegacyLanguageRedirect"],
  ["public", "/blog/*", "LegacyLanguageRedirect"],
  ["public", "/contact", "LegacyLanguageRedirect"],
  ["public", "/faq", "LegacyLanguageRedirect"],
  ["public", "/furniture/*", "LegacyLanguageRedirect"],
  ["public", "/landing/*", "LegacyLanguageRedirect"],
  ["public", "/locations/*", "LegacyLanguageRedirect"],
  ["public", "/materials/*", "LegacyLanguageRedirect"],
  ["public", "/privacy", "LegacyLanguageRedirect"],
  ["public", "/process", "LegacyLanguageRedirect"],
  ["public", "/products/*", "LegacyLanguageRedirect"],
  ["public", "/projects/*", "LegacyLanguageRedirect"],
  ["public", "/promotions", "LegacyLanguageRedirect"],
  ["public", "/quote", "LegacyLanguageRedirect"],
  ["public", "/services/*", "LegacyLanguageRedirect"],
  ["public", "/terms", "LegacyLanguageRedirect"],
];

test('all existing route identities survive shared admin definitions', () => {
  assert.deepEqual(readInteractionRoutes(fileURLToPath(new URL('..', import.meta.url))).map(({ surface, path, component }) => [surface, path, component]), previousRoutes);
});

test('finite AST parsing does not execute loader or role expressions', () => {
  const definitions = readAdminRouteDefinitionPaths('const adminRouteDefinitions = { example: defineRoute("content/:type/:id?", () => { throw Error("must not run"); }, externalRoles()) };');
  assert.equal(definitions.get('example'), 'content/:type/:id?');
});

test('computed and spread path definitions fail rather than hiding routes', () => {
  assert.throws(() => readAdminRouteDefinitionPaths('const adminRouteDefinitions = { example: defineRoute(getPath(), loader, roles) };'), /literal/);
  assert.throws(() => readAdminRouteDefinitionPaths('const adminRouteDefinitions = { ...otherRoutes };'), /literal/);
});
